In [2]:
import numpy as np

array

In [5]:
myArray=[20,30,40]   
#list

In [6]:
np.array(myArray)
#np array

array([20, 30, 40])

In [7]:
matrixList=[[10,20,30],[20,30,40],[40,80,60]]
#list

In [8]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [40, 80, 60]])

# arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# linspace

In [16]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [18]:
np.linspace(0,20,3)
#eşit parçaya bölüyor

array([ 0., 10., 20.])

In [19]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# eye

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# random

In [28]:
np.random.randn()

-0.27312044087966175

In [30]:
np.random.randn(3)

array([ 1.16120976, -1.08820128, -0.64406358])

In [40]:
myRandom =np.random.randn(30)

In [41]:
np.random.randint(1,10)

6

In [38]:
np.random.randint(1,10,3)
#10 dahil değil 3 rastgele int deger verir

array([5, 4, 2])

# numpy array method

In [42]:
myRandom.reshape(5,6)

array([[-0.19675646, -0.71094157, -0.73866658, -0.58244273, -0.63528658,
         1.26670731],
       [ 0.18070282, -1.37716495,  3.46713646,  0.30311748,  1.01202167,
        -0.18734982],
       [ 0.02918692,  0.48592236,  1.84310088, -0.50447329,  1.56722113,
        -0.69300977],
       [-1.02743597, -0.9607789 , -0.80196463, -1.51229636, -0.33525031,
        -0.44546005],
       [-1.24776885,  1.8781398 ,  0.22248833,  0.01150443, -0.52287185,
        -0.28442871]])

In [43]:
myRandom.min()

-1.5122963550114121

In [44]:
myRandom.max()

3.4671364574475847

In [45]:
myRandom.mean()

-0.016569926656751947

In [46]:
myRandom.argmax()

8

In [48]:
myRandom.sum()

-0.4970977997025584

# indexs 

In [52]:
myArrayX = np.arange(0,15)

In [53]:
myArrayX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
myArrayX[5]

5

In [55]:
myArrayX[4:7]

array([4, 5, 6])

In [56]:
myArrayX[4:14:2]

array([ 4,  6,  8, 10, 12])

In [57]:
myArrayX[4:7]=-5

In [58]:
myArrayX

array([ 0,  1,  2,  3, -5, -5, -5,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
otherArray=np.arange(0,24)

In [60]:
slicingDizi=otherArray[4:9]

In [61]:
slicingDizi

array([4, 5, 6, 7, 8])

In [62]:
otherArray


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [63]:
slicingDizi[:]=400

In [64]:
slicingDizi

array([400, 400, 400, 400, 400])

In [65]:
otherArray

array([  0,   1,   2,   3, 400, 400, 400, 400, 400,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# matrix

In [74]:
listx=[[1,2,4],[5,67,4],[12,13,14]]
ornekMatrix=np.array(listx )

In [75]:
ornekMatrix

array([[ 1,  2,  4],
       [ 5, 67,  4],
       [12, 13, 14]])

In [76]:
ornekMatrix[1,1]

67

In [77]:
ornekMatrix[0,0]

1

In [78]:
ornekMatrix[2]

array([12, 13, 14])

In [80]:
ornekMatrix[[1,2]]

array([[ 5, 67,  4],
       [12, 13, 14]])

#operations 

In [87]:
newArray= np.random.randint(5,100,20)

In [88]:
newArray

array([33, 16, 21, 11, 77, 94, 65, 70, 59, 32, 88, 10, 49,  5, 27, 56, 69,
       52, 19, 26])

In [89]:
newArray>24

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True])

In [90]:
newArray[newArray>24]

array([33, 77, 94, 65, 70, 59, 32, 88, 49, 27, 56, 69, 52, 26])

In [91]:
newArray

array([33, 16, 21, 11, 77, 94, 65, 70, 59, 32, 88, 10, 49,  5, 27, 56, 69,
       52, 19, 26])

In [97]:
sonDizi=np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [98]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [99]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [100]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [101]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [103]:
np.max(sonDizi)

23